
name: Package.JSON version set through workflow

on:
  push

    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG-Version: v1.0.35
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get tag semantic version
        uses: bhowell2/github-substring-action@1
        id: two
        with:
          value: ${{env.TAG-Version}}
          index_of_str: "v"
      # steps.one.outputs.substring = '1.0.35'
        
      - name: Update package.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: webapp/package.json
          field: version
          value: ${{steps.one.outputs.substring}}

      - name: Upload package.json
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: webapp/package.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply package version change
          
#      - name: Commit package files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add -A
#          git commit -m "docs(): bumping release $TAG-Version"
#          git tag TAG-Version
       
#      - name: Push changes
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          github_token: ${{ secrets.APIKEY }}
#          tags: false
      
#      - name: Set up Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: 14
