name: Release with artefacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Create release_build directory
        run: mkdir release_build
      - name: Copy all SQL to SQL inside release_build
        run:  cp -R SQL/ release_build/SQL/
## https://www.cyberciti.biz/faq/how-to-zip-a-folder-in-ubuntu-linux/
      - name: ZIP release_build
        run:  |
          zip -r release.zip release_build/
      - name: Release
#       Ref: https://github.com/softprops/action-gh-release      
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.md
            release.zip
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.APIKEY }}
#            SQL/*.sql