on: 
  milestone:
    types: [closed]

name: Release triggered by closing milestone
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: Decathlon/release-notes-generator-action@v3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
        
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          SQL
          webapp/build/
          api/bin/
          *.md
          !path/**/*.tmp
