## A Steps that will generate a release with notes and produces release artefacts


## Requirements:
## APIKEY - a github token access token that can publish into releases


name: Release with artefacts

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # populates variable ${{steps.tag.outputs.tag}}
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        
      - name: Get tag semantic version
        uses: bhowell2/github-substring-action@1
        id: two
        with:
          value: ${{steps.tag.outputs.tag}}
          index_of_str: "v"
    # steps.one.outputs.substring = 'c123' -- note length_from_start is ignored        
        
      - name: Update package.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: webapp/package.json
          field: version
          value: ${{steps.one.outputs.substring}}
          
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Generate Release notes
        run: |
          npm install github-release-notes -g
          export GREN_GITHUB_TOKEN=${{ secrets.APIKEY }}          
          gren changelog --generate --override --changelog-filename=RELEASE_NOTES.md
      
      - name: Create release_build directory
        run: mkdir release_build
      
      - name: Copy all SQL to SQL inside release_build
        run:  cp -R SQL/ release_build/SQL_${{steps.tag.outputs.tag}}/
      
      - name: Copy all webapp build
        run:  cp -R webapp/build/ release_build/webapp_${{steps.tag.outputs.tag}}/
      
      - name: ZIP release_build
        run:  |
          zip -r release.zip release_build/
      
      - name: Release
#       Ref: https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE_NOTES.md
          files: |
            *.md
            release.zip
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.APIKEY }}
