name: Release with artefacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Generate Release notes
        run: |
          npm install github-release-notes -g
          export GREN_GITHUB_TOKEN=${{ secrets.APIKEY }}          
          gren changelog --generate --override --changelog-filename=RELEASE_NOTES.md
      - name: Create release_build directory
        run: mkdir release_build
      - name: Copy all SQL to SQL inside release_build
        run:  cp -R SQL/ release_build/SQL_${{GITHUB_REF}}/
      - name: Copy all webapp build
        run:  cp -R webapp/build/ release_build/webapp_${{GITHUB_REF}}/

## https://www.cyberciti.biz/faq/how-to-zip-a-folder-in-ubuntu-linux/
      - name: ZIP release_build
        run:  |
          zip -r release.zip release_build/
      - name: Release
#       Ref: https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE_NOTES.md
          files: |
            *.md
            release.zip
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.APIKEY }}