name: Release with artefacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
#SRC: https://github.com/marketplace/actions/zip-release        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Release
#       Ref: https://github.com/softprops/action-gh-release      
        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            SQL/*.sql
            *.md
            release.zip
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.APIKEY }}
